- name: Install kibana
  yum: name=kibana
  notify: Restart kibana
  tags: install

  # Settings
  
- name: Transfer [conf.d/kibana.conf]
  copy: src={{ templates_path }}/httpd_conf.d/kibana.conf
            dest={{ httpd_conf_dir }}/conf.d/kibana.conf
  notify: Restart httpd
  tags: settings

- name: Transfer [etc/kibana/kibana.yml]
  copy: src={{ templates_path }}/etc_kibana_kibana.yml
            dest=/etc/kibana/kibana.conf
  notify: Restart kibana
  tags: settings

