require 'yaml'
ansible_settings = YAML.load_file './provision/ansible/group_vars/localhost/all.yml'

Vagrant::Config.run do |config|
  config.vm.box = ansible_settings['vm_box_name']
  config.vm.box_url = ansible_settings['vm_box_url']
end

Vagrant.configure("2") do |config|
  config.vm.box = ansible_settings['vm_box_name']

  config.vm.hostname = ansible_settings['domain']
  config.hostsupdater.aliases = ["tomcat.dazed.vagrant.vm","mailcatcher.dazed.vagrant.vm","kibana.dazed.vagrant.vm"]

   config.vm.network "forwarded_port", guest: 80, host: 30000
   config.vm.network "forwarded_port", guest: 9200, host: 9200
   config.vm.network "forwarded_port", host: 1080, guest: 1080

  config.vm.network :"private_network", ip: ansible_settings['ip_address'], auto_network: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = ansible_settings['memory']
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", ansible_settings['cpu_execution_cap']]
    file_to_disk = "tmp/disk.vdi"
    if not File.exist?(file_to_disk) then
      vb.customize ["createhd",
                    "--filename", file_to_disk,
                    "--size", ansible_settings['disk_size'] * 1024]
    end
    vb.customize ['storageattach', :id,
                  '--storagectl', 'SATA Controller',
                  '--port', 1,
                  '--device', 0,
                  '--type', 'hdd',
                  '--medium', file_to_disk]
  end

  config.vm.synced_folder "share", "/var/www/",
     :create => true,
     mount_options: ['nolock,vers=3,tcp,noatime'],
     :nfs => ansible_settings['nfs_enable']

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = ansible_settings['ansible_verbose']
    ansible.playbook = "provision/ansible/playbook/webservers.yml"
    ansible.inventory_path = "provision/ansible/hosts/localhost"
    ansible.limit = 'all'
  end
end
