Vagrant::Config.run do |config|
  config.vm.box = "centos6-64bit"
  config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box"
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos6-64bit"

  config.vm.hostname = "dazed.vagrant.vm"
  config.hostsupdater.aliases = ["tomcat.dazed.vagrant.vm","mailcatcher.dazed.vagrant.vm","kibana.dazed.vagrant.vm"]
   config.vm.network "forwarded_port", guest: 80, host: 30000
   config.vm.network "forwarded_port", guest: 9200, host: 9200
   config.vm.network "forwarded_port", host: 1080, guest: 1080

  config.vm.network :"private_network", ip: "192.168.33.10", auto_network: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    file_to_disk = "./tmp/disk.vdi"
    if not File.exist?(file_to_disk) then
      vb.customize ["createhd",
                    "--filename", file_to_disk,
                    "--size", 20 * 1024]
    end
    vb.customize ['storageattach', :id,
                  '--storagectl', 'SATA Controller',
                  '--port', 1,
                  '--device', 0,
                  '--type', 'hdd',
                  '--medium', file_to_disk]
  end

  config.vm.synced_folder "share", "/var/www/",
     :create => true,
     owner: "vagrant",
     group: "vagrant",
     mount_options: ['dmode=777','fmode=666'],
     :nfs => false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/ansible/webservers.yml"
    ansible.inventory_path = "provision/ansible/localhost"
    ansible.limit = 'all'
  end
end
