# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos6-64bit"

  config.vm.hostname = "dazed-vagrant.vm"
#  config.hostmanager.enabled = true
#  config.hostmanager.manage_host = true
#  config.hostmanager.aliases = aliases
  config.hostsupdater.aliases = ["tomcat.dazed-vagrant.vm","mailcatcher.dazed-vagrant.vm"]

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
   config.vm.network "forwarded_port", guest: 80, host: 30000
   config.vm.network "forwarded_port", guest: 9200, host: 9200
   config.vm.network "forwarded_port", host: 1080, guest: 1080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :"private_network", ip: "192.168.33.10", auto_network: true

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "share", "/var/www/html",
     :create => true,
     owner: "vagrant",
     group: "vagrant",
     mount_options: ['dmode=777','fmode=666'],
     :nfs => false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  
  PATH_WWW="/var/www/html"
  PATH_OPT="/opt"
  ADMIN="admin"
  PATH_HOME="/home/vagrant"
  PHP_TIMEZONE="Asia\/Tokyo"
  DOMAINNAME="dazed-vagrant.vm"

  # Middleware
  config.vm.provision :shell, :path => "provision/middleware/basic.sh", :args => [PATH_WWW,PATH_OPT]
  config.vm.provision :shell, :path => "provision/middleware/bash_profile.sh"
  config.vm.provision :shell, :path => "provision/middleware/location.sh"
  config.vm.provision :shell, :path => "provision/middleware/firewall_selinux.sh"
  config.vm.provision :shell, :path => "provision/middleware/apache.sh", :args => [PATH_WWW,ADMIN,DOMAINNAME]

  config.vm.provision :shell, :path => "provision/middleware/scm/scm.sh"
  config.vm.provision :shell, :path => "provision/middleware/scm/bash_it.sh", :args => [PATH_OPT,PATH_HOME], privileged: false

  config.vm.provision :shell, :path => "provision/middleware/mysql.sh"
  config.vm.provision :shell, :path => "provision/middleware/memcached.sh"
  config.vm.provision :shell, :path => "provision/middleware/image_magick.sh"
  config.vm.provision :shell, :path => "provision/middleware/php56.sh", :args => [PHP_TIMEZONE]

  config.vm.provision :shell, :path => "provision/middleware/java/java8.sh"
  config.vm.provision :shell, :path => "provision/middleware/java/tomcat.sh", :args => [PATH_OPT,"-server -Xmx128M -Xms64M -XX:MaxPermSize=256m",DOMAINNAME]
  config.vm.provision :shell, :path => "provision/middleware/java/elasitcsearch.sh", :args => ["128m","-XX:ParallelGCThreads=5"]

  config.vm.provision :shell, :path => "provision/middleware/ruby/ruby.sh", :args => [PATH_OPT]
  config.vm.provision :shell, :path => "provision/middleware/ruby/mailcatcher.sh", :args => [PATH_OPT,DOMAINNAME]

  config.vm.provision :shell, :path => "provision/middleware/enhancement.sh"

  # Application
  config.vm.provision :shell, :path => "provision/html/admin/index.sh", :args => [PATH_WWW,ADMIN,DOMAINNAME], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/phpinfo.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/phpmyadmin.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/phpMemcachedAdmin.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/opcache.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/memcache-test.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/mail-test.sh", :args => [PATH_WWW,ADMIN], privileged: false
  config.vm.provision :shell, :path => "provision/html/admin/apcu.sh", :args => [PATH_WWW,ADMIN], privileged: false

  # CMS
  config.vm.provision :shell, :path => "provision/cms/drupal8.sh", :args => [PATH_WWW], privileged: false
  config.vm.provision :shell, :path => "provision/cms/drupal7.sh", :args => [PATH_WWW], privileged: false
  config.vm.provision :shell, :path => "provision/cms/wordpress.sh", :args => [PATH_WWW], privileged: false

  config.vm.provision :shell, :path => "provision/home.sh", :args => [PATH_HOME,PATH_WWW,ADMIN], privileged: false

end
