- name: Install Logstash
  yum: name=logstash
  tags: install

# Settings
 
- name: Transfer [logstash logstash.yml]
  template: src={{ templates_path }}/logstash.yml
           dest=/etc/logstash.yml
  tags: settings

- name: Transfer [Logstash log4j2.properties]
  template: src={{ templates_path }}/log4j2.properties
           dest=/etc/log4j2.properties
  tags: settings

- name: Transfer [logstash jvm.options]
  template: src={{ templates_path }}/jvm.options
           dest=/etc/jvm.options
  tags: settings


