# Ruby

- include: ../ruby.yml

# Redmine

- name: Install dependent
  yum: name={{ item }}
  with_items:
    - "@development-tools"
    - openssl-devel
    - readline-devel
    - zlib-devel
    - curl-devel
    - libyaml-devel
    - libffi-devel
    - httpd-devel
    - ImageMagick
    - ImageMagick-devel
    - ipa-pgothic-fonts

- name: gem install bundler
  become_user: vagrant
  gem: name=bundler state=present

- name: Create redmine database
  become_user: vagrant
  mysql_db: name={{ redmine_db_name }} state=present
  register: exists_db_flag

- name: Svn checkout Redmine
  become_user: vagrant
  subversion: repo={{ redmine_svn_url }} dest={{ redmine_dir }}

- name: Add mysql user
  become_user: vagrant
  mysql_user: name={{ redmine_db_user }} password={{ redmine_db_passwd }} priv="{{ redmine_db_name }}.*:ALL"

- name: database.yml
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.yml
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml

- name: install gem package
  become_user: vagrant
  bundler:
    state: present
    exclude_groups: "development"
    gem_path: "vendor/bundle"
    chdir: "{{ redmine_dir }}"
    executable: /opt/rh/rbenv/shims/bundle

- name: secret tokenの作成
  become_user: vagrant
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production

- name: データベースのマイグレーション
  become_user: vagrant
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production

- name: デフォルトデータ(日本語)をロード
  become_user: vagrant
  command:
    bundle exec rake redmine:load_default_data
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
    REDMINE_LANG: ja
  when:
    result_database_yml|changed

- name: farend_basicテーマのダウンロード
  become_user: vagrant
  git:
    repo=https://github.com/farend/redmine_theme_farend_basic.git
    dest={{ redmine_dir }}/public/themes/farend_basic

- name: テーマをfarend_basicに切り替え
  become_user: vagrant
  command:
    bundle exec rails r 'Setting["ui_theme"]="farend_basic"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed

- name: デフォルトの言語を日本語に変更
  become_user: vagrant
  command:
    bundle exec rails r 'Setting["default_language"]="ja"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed

- name: ユーザー名の表示形式を「姓 名」に変更
  become_user: vagrant
  command:
    bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed

- name: 添付ファイルとリポジトリのエンコーディングを設定
  become_user: vagrant
  command:
    bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed

- name: 添付ファイルのサムネイルを表示
  become_user: vagrant
  command:
    bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed
