# Ruby

- include: ../ruby.yml

# Redmine

- name: Install dependent
  yum: name={{ item }}
  with_items:
    - "@development-tools"
    - openssl-devel
    - readline-devel
    - zlib-devel
    - curl-devel
    - libyaml-devel
    - libffi-devel
    - httpd-devel
    - ImageMagick
    - ImageMagick-devel
    - ipa-pgothic-fonts

- name: gem install bundler
  become_user: vagrant
  gem: name=bundler state=present

- name: Create redmine database
  become_user: vagrant
  mysql_db: name={{ redmine_db_name }} state=present
  register: exists_db_flag

- name: Svn checkout Redmine
  become_user: vagrant
  subversion: repo={{ redmine_svn_url }} dest={{ redmine_dir }}

- name: Add mysql user
  become_user: vagrant
  mysql_user: name={{ redmine_db_user }} password={{ redmine_db_passwd }} priv="{{ redmine_db_name }}.*:ALL"

- name: database.yml
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.yml
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml

- name: install gem package
  become_user: vagrant
  bundler:
    state: present
    exclude_groups: "development"
    gem_path: "vendor/bundle"
    chdir: "{{ redmine_dir }}"
