- hosts: webservers
  become: yes
  become_user: root
  roles:
    - common
    - firewall_selinux
    - imagemagick
    - scm
    - httpd
    - mysqld
    - memcached
    - php
    - enhancement
    - ruby/mailcatcher
    - java/tomcat
    - java/elasticsearch/elasticsearch
    - java/elasticsearch/kibana
    - java/elasticsearch/logstash
    - users
    - www


