- name: Disable original(v7.1) PHP-FPM
  service: name=php-fpm state=stopped enabled=no

- name: Disable PHP56-PHP-FPM
  service: name=php56-php-fpm state=stopped enabled=no
  ignore_errors: true

- name: Install php55
  yum: name={{ item }} enablerepo=remi,remi-php55
  with_items:
    - php55
    - php55-php-fpm
    - php55-php-cli
    - php55-php-common
    - php55-php-devel
    - php55-php-gd
    - php55-php-intl
    - php55-php-mbstring
    - php55-php-pdo
    - php55-php-mysqlnd
    - php55-php-pear
    - php55-php-xml
    - php55-php-mcrypt
    - php55-php-soap
  notify: restart php-fpm

- name: Install php55-PECL
  yum: name={{ item }} enablerepo=remi,remi-php55
  with_items: 
    - php55-php-pecl-imagick
    - php55-php-opcache
    - php55-php-pecl-memcache
    - php55-php-pecl-memcached
    - php55-php-pecl-apcu
    - php55-php-pecl-xdebug
  notify: restart php-fpm

- name: Create PHP log directory
  file: 
    path: /opt/remi/php55/root/var/log/php/
    state: directory
    owner: "vagrant"
    group: "vagrant"
    mode: 775

- name: Create PHP log file
  file: 
    path: /opt/remi/php55/root/var/log/php/php_errors.log
    state: touch
    owner: "vagrant"
    group: "vagrant"
    mode: 775

- name: Change the php.ini
  replace:
    dest: "/opt/remi/php55/root/etc/php.ini"
    regexp: '{{ item.regexp}}'
    replace: '{{ item.replace }}'
  with_items: 
    - regexp: '^;(date.timezone) =.*'
      replace: 'date.timezone = {{ php_timezone }}'
    - regexp: '^(memory_limit) =.*'
      replace: 'memory_limit = {{ php_memory_limit }}'
    - regexp: '^display_errors = Off'
      replace: 'display_errors = On'
    - regexp: '^;error_log = php_errors.log'
      replace: 'error_log = /opt/remi/php55/root/var/log/php/php_errors.log'
    - regexp: '^disable_functions =.*'
      replace: 'disable_functions = {{ php_disable_functions }}'
  notify: restart php-fpm

- name: Change the php-fpm.d/www.conf
  replace:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: '{{ item.regexp}}'
    replace: '{{ item.replace }}'
  with_items: 
    - regexp: '^listen = 127.0.0.1:90..'
      replace: 'listen = 127.0.0.1:{{ php55_fpm_port }}'
  notify: restart php-fpm

- name: Change the vhosts
  replace:
    dest: "/etc/httpd/conf.d/vhost.conf"
    regexp: '{{ item.regexp}}'
    replace: '{{ item.replace }}'
  with_items: 
    - regexp: 'proxy:fcgi://127.0.0.1:90..'
      replace: 'proxy:fcgi://127.0.0.1:{{ php55_fpm_port }}'
  notify: restart webserver

