- name: Check the additional partition directory
  shell: df | grep /dev/sdb
  register: mount_result
  failed_when: mount_result.rc not in [0, 1]

- name: yum install xfsprogs
  yum:
    name: xfsprogs
  when: mount_result.rc == 1 and mount_file_system == "xfs"

- name: mkfs
  filesystem:
    fstype: "{{ mount_file_system }}"
    dev: "{{ mount_device }}"
  when: mount_result.rc == 1

- name: mkdir opt_dir
  file:
    path: "{{ opt_dir }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: ug+rw
    state: directory
  when: mount_result.rc == 1

- name: get blkid
  shell: 'blkid {{ mount_device }} | awk -F\" ''{ print $2 }'' '
  register: uuid
  when: mount_result.rc == 1

- name: mount
  mount:
    name: "{{ opt_dir }}"
    src: "UUID={{ uuid.stdout }}"
    fstype: "{{ mount_file_system }}"
    opts: defaults
    state: mounted
  when: mount_result.rc == 1
