production:
  ui_theme: redmine-theme-gitmike-design
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "localhost"
      port: 25
      domain: "{{ ansible_fqdn }}"

  rmagick_font_path: {{ redmine_font_path }}