
#- name: Remove [ php ]
#  yum: name=php* state=absent
#  tags: install

- name: Install epel-release
  yum: name=epel-release state=present
  tags: install

- name: Install remi-release-6.rpm
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
  tags: install

- name: Install remi-release-7.rpm
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  tags: install

- name: Install php
  yum: name={{ item }} enablerepo=remi,remi-php{{ php_version }}
  with_items: "{{ php_required_modules }}"
  notify: Restart php-fpm
  tags: install

- name: Install PECL
  yum: name={{ item }} enablerepo=remi,remi-php{{ php_version }}
  with_items: "{{ php_required_pecl_modules }}"
  notify: Restart php-fpm
  tags: install

- name: Create folder [php log]
  file: path={{ log_dir }}/php
         state=directory
         owner={{ owner }}
         group={{ owner }}
         mode=775
  tags: install

- name: Touch php/php-error.log
  file: path={{ log_dir }}/php/php_errors.log
         state=touch
         owner={{ owner }}
         group={{ owner }}
         mode=644
  tags: install

- name: Transfer /etc/logrotate.d/php
  template: src={{ templates_path }}/etc_logrotate.d/php
        dest=/etc/logrotate.d/php
        owner=root
        group=root
        mode=0644
  tags: install

- name: Change the php.ini
  replace:
    dest: "/etc/php.ini"
    regexp: '{{ item.regexp}}'
    replace: '{{ item.replace }}'
  with_items: 
    - regexp: '^;(date.timezone) =.*'
      replace: 'date.timezone = {{ php_timezone }}'
    - regexp: '^(memory_limit) =.*'
      replace: 'memory_limit = {{ php_memory_limit }}'
    - regexp: '^display_errors = Off'
      replace: 'display_errors = On'
    - regexp: '^;error_log = php_errors.log'
      replace: 'error_log = /var/log/php/php_errors.log'
    - regexp: '^disable_functions =.*'
      replace: 'disable_functions = {{ php_disable_functions }}'
  notify: Restart php-fpm


- name: Permission change /var/lib/php/
  file: path={{ item }}
        state=touch
        owner={{ owner }}
        group={{ owner }}
        mode=777
  with_items:
    - /var/lib/php/
    - /var/lib/php/opcache
    - /var/lib/php/opcache
    - /var/lib/php/session
    - /var/lib/php/wsdlcache
  tags: install

#- name: Transfer httpd/conf.d/php.conf
#  template: src={{ templates_path }}/httpd_conf.d/php7.conf
#        dest={{ httpd_conf_dir }}/conf.d/php.conf
#        owner={{ owner }}
#        group={{ owner }}
#        mode=0664
#  notify: Restart httpd
#  tags: settings

