## For vagrant ##
domain: "dazed.vagrant.vm"
ip_address: "192.168.33.11"
vm_box_name: "CommanderK5/Centos7.2" # centos/7 or centos/6 or Custom: CentOS7.1
vm_box_define_name: "dazed"
site_name: "Dazed and confused vagrant VM"
vm_box_url: "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box"
ansible_playbook: "provision/vagrant_build.yml"
ansible_version: "2.4.2.0"
mount_file_system: ext4
memory: 2048 # 2GB
disk_size: "10GB" # 40GB
cpu_execution_cap: 80 # 80%
synced_folders_type: "nfs" #
ansible_verbose: "vv"
share_dir: /var/www/vagrant

# User setting
mycolor: $'32m'

# Common
opt_dir: /opt/rh
templates_path: ../templates
files_path: ../files
env_dir: vagrant
env_mode: vagrant
owner: vagrant
group: vagrant
permission: "ugo+rw"
permission_file: 0666
permission_dir: 0777
time_zone: Tokyo/Asia
log_dir: /var/log
tools_dir: /opt/rh/tools

# For JAVA
java_versions: java-1.8.0-openjdk-devel.x86_64
java_home: /usr/java/jdk1.7.0_80

# For Tomcat
tomact_dir: "{{ opt_dir }}/tomcat"
tomcat_user: vagrant
tomcat_group: vagrant
tomcat_name: tomcat8
tomcat_Xms: 128M
tomcat_Xmx: 1024M
tomcat_maxThreads: 100

# For Elasticsearch
elastic_conf_dir: /etc/elasticsearch
elastic_user: vagrant
elastic_group: vagrant

# Httpd
apache_user: vagrant
apache_group: vagrant
httpd_conf_dir: /etc/httpd
httpd_document: "{{share_dir }}"
httpd_document_root: "{{ httpd_document }}/html"
httpd_log_dir: "{{ log_dir }}/httpd"
httpd_version: httpd
httpd: httpd
ssl_certificate_path: "{{ opt_dir }}/ssl-client-auth"
ssl_certificate_file: "{{ opt_dir }}/ssl-client-auth/dazed.vagrant.vm.crt"
ssl_certificate_key_file: "{{ opt_dir }}/ssl-client-auth/server.key"
ssl_certificate_chain_file: "{{ opt_dir }}/ssl-client-auth/root_ca.crt"
httpd_module_path: /usr/lib64/httpd/modules

# PHP
php_memory_limit: 512M
php_version: 71 # Example: 71, 70, 56, 55
phpfpm_port: 9000

# MySQL
mysq_user: mysql
mysq_group: mysql
mysql_root_user: root
mysql_root_passwd: root

# www/cms
drupal7: drupal7
drupal8: drupal8
wordpress: wordpress
drupal7_version: drupal-7.54
drupal8_version: drupal-8.2.6
wordpress_version: wordpress-4.7.2-ja

