- name: Add to /etc/environment
  lineinfile:
    dest=/etc/environment
    line={{ item }}
  with_items:
    - 'RAILS_ENV=production'

- name: Permission change /opt/rh
  file: path={{ rbenv_path }}
        state=directory
        owner={{ owner }}
        group={{ group }}
        mode=775

- name: Git clone rbenv
  git: repo=git://github.com/sstephenson/rbenv.git
       dest={{ rbenv_path }}/rbenv
       version=master
  become_user: "{{ owner }}"
  ignore_errors: True
  tags: install

- name: Git clone ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest={{ rbenv_path }}/rbenv/plugins/ruby-build
       version=master
  become_user: "{{ owner }}"
  ignore_errors: True
  tags: install

- name: Change Permission
  file: path={{ rbenv_path }}/rbenv/
        state=directory
        owner={{ owner }}
        group={{ group }}
        mode=ug+rw

- name: Add to /etc/profile
  lineinfile:
    dest=/etc/profile
    line={{ item }}
  with_items:
    - ''
    - '# RBENV'
    - 'export RBENV_ROOT="{{ rbenv_path }}/rbenv"'
    - 'export PATH="${RBENV_ROOT}/bin:${PATH}"'
    - 'eval "$(rbenv init -)"'
  tags: install

- name: Install dependent
  yum: name={{ item }}
  with_items:
    - gcc
    - make
    - openssl-devel
    - libffi-devel
    - readline-devel
  tags: install

- name: Add [ city-fan.org repos ]
  yum: name=http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-2-1.rhel7.noarch.rpm
  tags: install
  
- name: Update [ libcurl ]
  yum: name=libcurl enablerepo=city-fan.org state=latest

- name: Permission change /opt/rh
  file: path={{ rbenv_path }}
        state=directory
        owner={{ owner }}
        group={{ group }}
        recurse=Yes
        mode=775

- name: Install Ruby
  command: bash -lc "rbenv install {{ ruby_version }}"
  ignore_errors: yes
  become_user: "{{ owner }}"
  tags: install

- name: Do rehash
  command: bash -lc "rbenv rehash"
  become_user: "{{ owner }}"
  tags: install

- name: Set Target Ruby version as default
  command: bash -lc "rbenv global {{ ruby_version }}"
  become_user: "{{ owner }}"
  tags: install

- name: Do rehash
  command: bash -lc "rbenv rehash"
  become_user: "{{ owner }}"
  tags: install

