# Install

#- name: Remove [ httpd ]
#  yum: name=httpd state=absent
#  tags: install

#- name: Remove [ /etc/httpd ]
#  file: path=/etc/httpd state=absent
#  tags: install

#- name: Download apache 2.4 repos
#  get_url: url=https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo
#           dest=/etc/yum.repos.d/
#  tags: install

#- name: Install [ httpd24-httpd ]
#  yum: name={{ item }} enablerepo=epel-httpd24 state=present
#  with_items:
#    - openssl
#    - httpd24-httpd
#    - httpd24-mod_ssl
#    - httpd24-apr
#  notify: Restart httpd
#  tags: install

- name: Install [ httpd ]
  yum: name={{ item }} state=present
  with_items:
    - openssl
    - httpd
    - mod_ssl
  notify: Restart httpd
  tags: install

#- name: Create httpd symbolic link
#  file:
#    src={{ httpd_conf_dir }} dest=/etc/httpd state=link
#  tags: install

- name: self signed certificate
  shell: |
    crt_file="/etc/pki/tls/certs/{{ domain }}.crt" &&
    key_file="/etc/pki/tls/private/{{ domain }}.key" &&
    crt_and_key_file="/etc/pki/tls/private/{{ domain }}.crt_and_key" &&
    subject="/C=JP/ST=Tokyo/L=Tokyo City/CN={{ domain }}" &&
    openssl req -new -newkey rsa:2048 -sha1 -x509 -nodes \
      -set_serial 1 \
      -days 3650 \
      -subj "$subject" \
      -out "$crt_file" \
      -keyout "$key_file" &&
    cat "$crt_file" "$key_file" >> "$crt_and_key_file" &&
    chmod 666 "$key_file" "$crt_and_key_file"
    creates="/etc/pki/tls/certs/{{ domain }}.crt"
  notify: Restart httpd

- name: Change modify [ Conf directory ]
  file: path={{ httpd_conf_dir }}
        owner={{ apache_user }}
        group={{ apache_group }}
        mode=ug+rw
        recurse=yes
  tags: install

- name: Create [ Log directory ]
  file: path={{ log_dir }}/httpd
        state=directory
        owner={{ apache_user }}
        group={{ apache_group }}
        mode=0755
  notify: Restart httpd

# Settings

- name: Transfer [httpd.conf]
  template: src={{ templates_path }}/httpd22.conf
        dest={{ httpd_conf_dir }}/conf/httpd.conf
  notify: Restart httpd
  tags: settings

- name: Transfer [vhost.conf]
  template: src={{ templates_path }}/conf.d/vhost.conf
        dest={{ httpd_conf_dir }}/conf.d/vhost.conf
  notify: Restart httpd
  tags: settings

- name: Transfer [ssl.conf]
  template: src={{ templates_path }}/conf.d/ssl22.conf
        dest={{ httpd_conf_dir }}/conf.d/0_ssl.conf
  notify: Restart httpd
  tags: settings

- name: Transfer [server-info.conf]
  template: src={{ templates_path }}/conf.d/server-info.conf
        dest={{ httpd_conf_dir }}/conf.d/server-info.conf
  notify: Restart httpd
  tags: settings

- name: Transfer [server-status.conf]
  template: src={{ templates_path }}/conf.d/server-status.conf
        dest={{ httpd_conf_dir }}/conf.d/server-status.conf
  notify: Restart httpd
  tags: settings


