# install

- name: Add mysql repo
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present
  tags: install

- name: Install MySQL
  yum: name=mysql-community-server
  tags: install

- name: Transfer my.cnf
  copy: src={{ templates_path }}/my.cnf
            dest=/etc/my.cnf
            owner={{ mysq_user }}
            group={{ mysq_group }}
            mode=0664
  notify: Restart mysqld
  tags: settings


- name: Be sure MySQL is running and enabled
  service: name=mysqld state=running enabled=yes
  tags: install

- name: Install MySQL-python (For ansible)
  yum: name=MySQL-python state=present
  tags: install

- name: Add root user of mysqld
  mysql_user: name="root" host={{ item }} password={{ mysql_root_passwd }}
  with_items:
    - 127.0.0.1
    - localhost
  ignore_errors: True
  tags: install

# log
- name: Create folder [mysqld log]
  file: path={{ log_dir }}/mysqld
         state=directory
         owner={{ mysq_user }}
         group={{ mysq_group }}
         mode=775
  tags: install

- name: Touch [mysqld/error.log]
  file: path={{ log_dir }}/mysqld/error.log
         state=touch
         owner={{ mysq_user }}
         group={{ mysq_group }}
         mode=644
  tags: install

- name: Touch [mysqld/slow_query.log]
  file: path={{ log_dir }}/mysqld/slow_query.log
         state=touch
         owner={{ mysq_user }}
         group={{ mysq_group }}
         mode=644
  tags: install

- name: Touch [mysqld/query.log]
  file: path={{ log_dir }}/mysqld/query.log
         state=touch
         owner={{ mysq_user }}
         group={{ mysq_group }}
         mode=644
  tags: install

# logrotate
- name: Transfer [logrotate.d/mysql]
  copy: src={{ templates_path }}/etc_logrotate.d/mysql
            dest=/etc/logrotate.d/mysql
            owner=root
            group=root
            mode=0644
  tags: install

