---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
    enabled: yes
  notify: restart php-fpm

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
