- name: Install dependent
  yum: name={{ item }}
  with_items:
    - "@development-tools"
    - openssl-devel
    - readline-devel
    - zlib-devel
    - curl-devel
    - libyaml-devel
    - libffi-devel
    - httpd-devel
    - ImageMagick
    - ImageMagick-devel
    - ipa-pgothic-fonts
    - mysql-devel

- name: Permission change /opt/rh
  file: path={{ rbenv_path }}
        state=directory
        owner={{ owner }}
        group={{ group }}
        mode=775

- name: gem install bundler
  become_user: "{{ owner }}"
  gem: name=bundler state=present executable=/opt/rh/rbenv/shims/gem user_install=False

- name: Install MySQL-python (For ansible)
  yum: name=MySQL-python state=present
  tags: install

- name: Create redmine database
  become_user: "{{ owner }}"
  mysql_db: name={{ redmine_db_name }} state=present encoding=utf8
  register: exists_db_flag


- name: Svn checkout Redmine
  become_user: "{{ owner }}"
  subversion: repo={{ redmine_svn_url }} dest={{ redmine_dir }}
  ignore_errors: True

- name: config/database.yml
  become_user: "{{ owner }}"
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.yml
  become_user: "{{ owner }}"
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml

- name: Add mysql user
  become_user: "{{ owner }}"
  mysql_user: name={{ redmine_db_user }} password={{ redmine_db_passwd }} priv="{{ redmine_db_name }}.*:ALL"


- name: bundle install --without development test --path vendor/bundle
  become_user: "{{ owner }}"
  bundler:
    state: present
    exclude_groups: "development"
    gem_path: "vendor/bundle"
    chdir: "{{ redmine_dir }}"
    executable: /opt/rh/rbenv/shims/bundle

- name: Create secret token
  become_user: "{{ owner }}"
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production

- name: bundle exec rake db:migrate
  become_user: "{{ owner }}"
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "{{ ruby_environment_path }}"
    RAILS_ENV: production

- name: Install passenger
  gem: name=passenger state=present user_install=False
  environment:
   PATH: "{{ ruby_environment_path }}"

- name: Install Passenger Apache module
  command:
    passenger-install-apache2-module --auto
  environment:
   PATH: "{{ ruby_environment_path }}"

- name: Get the settings from passenger apache module
  become_user: "{{ owner }}"
  command:
    passenger-install-apache2-module --snippet
  environment:
   PATH: "{{ ruby_environment_path }}"
  register:
    passenger_snippet_vars
  changed_when: false

- name: Add redmine.conf for apache
  template:
    src=httpd_conf_redmine.conf
    dest={{ httpd_conf_dir }}/conf.d/{{ redmine }}.conf
  notify: Restart httpd

- name: Change modify
  file: path={{ redmine_dir }}
         state=directory
         owner={{ apache_user }}
         group={{ group }}
         mode=ug+rw

- name: Install hg ( For pluigin )
  yum: name=hg state=present
  tags: install

